const fs=require('fs');
let html=''; const store={};
const app={set innerHTML(v){html=String(v)},get innerHTML(){return html}};
global.document={hidden:false,getElementById(id){return id==='app'?app:null},addEventListener(){},querySelector(){return null},querySelectorAll(){return []}};
global.localStorage={getItem(k){return store[k]||null},setItem(k,v){store[k]=String(v)}};
global.navigator={vibrate(){}};
global.location={protocol:'file:',hostname:''}; global.window=global;
global.requestAnimationFrame=(fn)=>fn(); global.setInterval=()=>0; global.setTimeout=()=>0;
global.Image=class{constructor(){this.complete=false;this.decode=null}set src(v){this._src=v}get src(){return this._src}};
let src=fs.readFileSync('web/app.js','utf8');
src=src.replace(/\}\)\(\);\s*$/, "globalThis.__slideTest={handle,state,render,dailyPuzzle,questState,achievements,continuePuzzle,totalStars,playerLevel};})();");
try{eval(src)}catch(e){console.error('LOAD ERROR',e.stack);process.exit(2)}
const assert=(c,m)=>{if(!c){console.error('ASSERT FAIL',m);console.error(html.slice(0,2500));process.exit(3)}};
assert(html.includes("TODAY'S GOALS"),'home goals');
assert(html.includes('CONTINUE JOURNEY'),'home continue');
assert(html.includes('profile-trigger'),'profile trigger');
const T=global.__slideTest;
T.handle('profile',{dataset:{}});
assert(html.includes('PLAYER CARD'),'profile card');
assert(html.includes('BADGES'),'badges');
assert(html.includes('SOUND'),'sound toggle');
assert((html.match(/class="achievement /g)||[]).length===6,'six achievements');
const old=T.state.profile.soundEnabled;
T.handle('toggle-sound',{dataset:{}});
assert(T.state.profile.soundEnabled!==old,'sound toggle works');
T.handle('back-profile',{dataset:{}});
T.handle('continue',{dataset:{id:'fantasy-01'}});
assert(T.state.screen==='game','continue launches game');
assert(T.state.profile.lastPlayed==='fantasy-01','last played persists in state');
T.state.won=true; T.state.moves=60; T.state.seconds=70;
T.state.lastResult={stars:3,improved:true,firstEverSolve:true,dailyBonus:0,questBonus:1,levelUp:false,collectionComplete:false,streak:1};
T.render();
assert(html.includes('GOALS +1 ★'),'quest win badge');
assert(html.includes('NEXT PUZZLE'),'win remains intact');
console.log('PASS v12 engagement smoke');
