const fs=require('fs');
let html=''; const store={};
const app={set innerHTML(v){html=String(v)},get innerHTML(){return html}};
global.document={hidden:false,getElementById(id){return id==='app'?app:null},addEventListener(){},querySelector(){return null},querySelectorAll(){return []}};
global.localStorage={getItem(k){return store[k]||null},setItem(k,v){store[k]=String(v)}};
global.navigator={vibrate(){}};
global.location={protocol:'file:',hostname:''};
global.window=global;
global.requestAnimationFrame=(fn)=>fn();
global.setInterval=()=>0; global.setTimeout=()=>0;
global.Image=class{constructor(){this.complete=false;this.decode=null}set src(v){this._src=v}get src(){return this._src}};
let src=fs.readFileSync('web/app.js','utf8');
src=src.replace(/\}\)\(\);\s*$/, "globalThis.__slideTest={handle,state,render,dailyPuzzle,collectionStats,dailyStreak,playerLevel,nextPuzzle,totalStars};})();");
try{eval(src)}catch(e){console.error('LOAD ERROR',e.stack);process.exit(2)}
const assert=(c,m)=>{if(!c){console.error('ASSERT FAIL',m);console.error(html.slice(0,2000));process.exit(3)}};
assert(html.includes('player-strip'),'home player strip');
assert(html.includes('DAILY #'),'home daily metadata');
assert(html.includes('week-strip'),'home weekly streak');
const T=global.__slideTest;
T.handle('collection',{dataset:{}});
assert(html.includes('COLLECTIONS'),'collection');
assert(html.includes('collection-meter'),'collection meter');
T.handle('filter',{dataset:{filter:'fantasy'}});
assert((html.match(/class="card"/g)||[]).length===10,'fantasy cards');
T.handle('play',{dataset:{id:'fantasy-02'}});
assert(html.includes('challenge-strip'),'game target');
assert(html.includes('SHUFFLE'),'game controls');
T.handle('guide',{dataset:{}});
assert(html.includes('QUICK GUIDE'),'quick guide');
T.handle('close-guide',{dataset:{}});
T.state.won=true;
T.state.moves=70; T.state.seconds=82;
T.state.lastResult={stars:3,improved:true,firstEverSolve:true,dailyBonus:2,levelUp:true,collectionComplete:false,streak:1};
T.render();
assert(html.includes('NEW TALE!'),'win new tale');
assert(html.includes('NEXT PUZZLE'),'next puzzle');
assert(html.includes('UP NEXT'),'next preview');
T.handle('home',{dataset:{}});
T.handle('daily',{dataset:{}});
assert(T.state.isDaily===true,'daily mode state');
console.log('PASS v11 retention smoke');
